# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for ticktick-mcp-server
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src
COPY oauth-helper.js ./oauth-helper.js

# Install and build
RUN npm install --ignore-scripts \
    && npm run build

# Default command
CMD ["node", "dist/index.js"]
